[package]
name = "city-server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-identity = "0.8.0"
actix-rt = "2.10.0"
actix-session = { version = "0.10.1", features = ["cookie-session"] }
actix-web = "4.11.0"
diesel = { version = "2.2.12", features = ["postgres", "r2d2"] }
dotenvy = "0.15.7"
serde = { version = "1.0.219", features = ["derive"] }

[profile.release]
lto = true
